apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: jackojack/domain-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-usr
            - name: PORT
              value: "8002"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: db-url
---

apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  type: ClusterIP
  selector:
    app: bot-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
