[build]
base = "back/"
command = "./build.sh"
functions = "functions"
publish = "public"

[build.environment]
GO_IMPORT_PATH = "https://github.com/HETIC-MT-P2021/PROJECT_FINAL_GROUP03"
GO111MODULE = "on"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/deploy/:splat"
status = 200
