name: Netlify-Preview

on:
  pull_request:
    branches: [main, develop]
    paths:
    - "./front"

jobs:

  build-deploy-preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Netlify Actions setup
      uses: nwtgck/actions-netlify@v1.2.2
      with:
          publish-dir: './front/build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
          netlify-config-path: './front/netlify.toml'
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      timeout-minutes: 1
    
      
