name: Netlify-Preview

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'front/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'front/**'

jobs:
  build-deploy-preview:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./front
        run: npm install

      - name: Build
        working-directory: ./front
        run: npm run build

      - name: Netlify prevew deploy
        uses: nwtgck/actions-netlify@v1.2.2
        with:
          publish-dir: './front/build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: true
          enable-commit-comment: false
          overwrites-pull-request-comment: true
          netlify-config-path: './front/netlify.toml'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

